### ISSUE TITLE
Create official Docker image

### ISSUE THREAD

**Issue by Spass1966** [BlueWallet/LndHub#32]
I have a clightning node already. I don't understand why I can't connect to it directly from BlueWallet but given the necessity of LndHub, I would like to request an easily configured Docker image.

**Comment by clonmac** [comment]
I run LndHub within Docker and given the fact that there is both a web front-end and DB backend, it is probably best practice to run both of those in separate containers. There is already an official redis and node image which is what is needed for running LndHub. 

Given the simplicity of redis, I don't need need to build my own image to use for LndHub, you can just specify your DB and config in variables when you run your container directly off the official redis image.

For the nodejs side of things, it is easy enough to just build your own image with a Dockerfile. Just copy in the github repo and 'RUN npm i' to build it out and copy in your config file and you're all set.

You'll need to be running LND for your lightning implementation though, not c-lightning.

**Comment by Spass1966** [comment]
Thank you for the detailed instruction, I will close this issue now.

**Comment by maltokyo** [comment]
@clonmac  would you mind to share your dockerfile and command to run it? Thank you!!

**Comment by clonmac** [comment]
This is what I have for mine. There are probably some better ways to do it that is more Docker "friendly" so that config file isn't built in the image and is rather in a volume or something, since that's not really best practice. But, since it's my personal image, it isn't too big of a deal for me. The Node.js project is within the /LndHub folder which gets copied into the image during the build. Some of the "npm" commands I had to add in there to get it to execute post-build. Some of them could probably be modified/removed, but it's been working for a while and I haven't had time to take a second look. Hope that's enough of a start at least. For the redis container, I just pull the official latest redis container for the DB.

```
FROM node:10-buster

RUN groupadd -r lndhubuser -g 1001 && useradd -d /home/lndhubuser -u 1001 -r -g lndhubuser lndhubuser

RUN mkdir /home/lndhubuser/ && chown -R 1001:1001 /home/lndhubuser/

COPY LndHub/ /lndhub/

WORKDIR /lndhub/

RUN npm install -g express

RUN npm install --save helmet

RUN npm i

RUN mkdir /lndhub/logs && chown -R 1001:1001 /lndhub/

USER lndhubuser

EXPOSE 3000

# Define default command
CMD /lndhub/node_modules/.bin/babel-node index.js
```

**Comment by maltokyo** [comment]
thank you very much @clonmac !  Will work off this, and try to build on it!

**Comment by maltokyo** [comment]
This worked well, thank you @clonmac 

I did, however, get continually this error/failure at the `npm i` step, would you know if it has any impact on the final container (which finished building overall)?  I tried to search for it, but could not find the impact of using the "Pure JS implementation".  No issues for you?

> Step 6/10 : RUN npm i
>  ---> Running in 1722afd7da14
> 
> > secp256k1@3.8.0 install /lndhub/node_modules/secp256k1
> > npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

**Comment by maltokyo** [comment]
Hi @clonmac I am coming back to this now as I have some time to work on it.  Would you please share your docker-compose.yml file as well?  Or the command you use to start it up and connect it to lnd?  Thank you!
