### ISSUE TITLE
Payment of invoice generated on the same LND as lndhub is not working

### ISSUE THREAD

**Issue by oparex** [BlueWallet/LndHub#62]
**Describe the problem/bug**
Can't pay an invoice generated on the same lnd node that lndhub is connected to.

**Your environment**
* Version lnd: 0.9.1-beta.rc1

**Logs**
```
Apr 06 10:25:26 chronos node[28240]: 2020-04-06T10:25:26.098Z : info: [/payinvoice] : ["c5f7f705-065a-423c-b84a-64571a3d08f0","userid: f06876e1557cd918d293eeb8823d6ff1c43c8b9542a34042","invoice: lnbc100u1p0gkqutpp5nt78fmsyt2vc7mydcmw5e0698z6kcd9eu94v3vxma7sgj878464sdqqcqzpgxqyz5vqsp5y2705f7yhuq82j0dgng7w5vv28phcxp27dhrvg45u49962q9m0rq9qy9qsqu5rlq089sum5n8wnh7ug9zdvqqn3zyzq7805chv3uy5apkgx9xrs4x2mudm2vyxqfuxr2ajtu05dhqwtfu5a36xj5z3l6nd3rkqnmccpkacw4x"]
Apr 06 10:25:26 chronos node[28240]: 2020-04-06T10:25:26.171Z : info: [/payinvoice] : ["c5f7f705-065a-423c-b84a-64571a3d08f0","userBalance: 33755","num_satoshis: 10000"]
Apr 06 10:25:26 chronos node[28240]: c5f7f705-065a-423c-b84a-64571a3d08f0 ::ffff:10.0.0.91 - - [06/Apr/2020:10:25:26 +0000] "POST /payinvoice HTTP/1.1" 200 80 "-" "BlueWallet/1585585391 CFNetwork/1121.2.2 Darwin/19.3.0"
```

**To Reproduce**
1. Connect lndhub to lnd
2. Create a lightning wallet in bluewallet
3. Create an invoice on lnd (lncli, joule, zap...)
4. Pay the invoice with bluewallet

**Expected behavior**
Pay the invoice. Nothing in lnd should actually happen. Only the ballance of the lndhub wallet should be subtracted. Also, payment_preimage should be sent to bluewallet (for LSAT usage or something else...)

**Actual behavior**
Invoice in not paid with error:
API error: Something went wrong. Please try again later (code 6)

**Additional context**
1. payment of invoices of other lnd nodes works fine
2. after checking router code for /payinvoice, I see this error can only be produced if lock is not obtained for redis. So I restarted redis and lndhub to flush any hanging connections. The problem was still the same.

**Comment by Overtorment** [comment]
feels like something is wrong with either your node id or the node id in the invoice.
we check if we are paying own invoice in `controllers/api.js:159`
`if (identity_pubkey === info.destination) {`
otherwise payment goes straight to lnd 

so can you put debug print there to see whats going on..?


we get `identity_pubkey` from lightning getInfo call. I even checked lnd grpc documentation to see maybe they changed format and broke some things but it is unchanged: https://api.lightning.community/?javascript#getinfo

default bluewallet's lndhub  runs lnd `v0.9.1` and everything works fine.  there are also integration tests for this specific functionality here:  https://github.com/BlueWallet/BlueWallet/blob/55b6ae998be2bff73d7fac9537d75a5b56278339/tests/integration/lightning-custodian-wallet.test.js#L226

**Comment by oparex** [comment]
```
id_pub:  0364f45ee43cd4b1d6db08972dfd6ab227e47adccee80ca7d76ae0bd107334c2aa
dest:  0364f45ee43cd4b1d6db08972dfd6ab227e47adccee80ca7d76ae0bd107334c2aa
identity_pubkey === info.destination:  true
userid:  null
```

pubkeys are ok, the program goes in local transfer execution path, but it cannot get payee. Isn't payee the one receiving the payment? how could this reference exist in db since I have generated the invoice outside off bluewallet/lndhub (I have generated the invoice with joule) ?

**Comment by Overtorment** [comment]
ok now I get it. well it should not work in your case, since invoice you create is not attached to any user on lndhub, lndhub does not know who is payee, so execution falls into:

```
        let userid_payee = await u.getUseridByPaymentHash(info.payment_hash);
        if (!userid_payee) {
          await lock.releaseLock();
          return errorGeneralServerError(res);
        }
```
